# Generated by Django 4.1.2 on 2023-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_crud', '0002_event_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
